format = """\
  $username\
  $hostname\
  $shlvl\
  $kubernetes\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $hg_branch\
  $docker_context\
  $package\
  $cmake\
  $dart\
  $dotnet\
  $elixir\
  $elm\
  $erlang\
  $golang\
  $helm\
  $java\
  $julia\
  $nim\
  $php\
  $purescript\
  $python\
  $ruby\
  $rust\
  $swift\
  $terraform\
  $zig\
  $nix_shell\
  $conda\
  $memory_usage\
  $aws\
  $gcloud\
  $env_var\
  $crystal\
  $cmd_duration\
  $time\
  $battery\
  $line_break\
  $jobs\
  $status\
  $character\
"""

[username]
show_always = true

[hostname]
ssh_only = false
style = "bold dimmed blue"

[directory]
format = ""
truncate_to_repo = false
truncation_length = 0

[memory_usage]
disabled = false
show_percentage = true
show_swap = true
threshold = -1
symbol = "ram: "

[time]
disabled = false
